<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * Bonfire
 *
 * An open source project to allow developers get a jumpstart their development of CodeIgniter applications
 *
 * @package   Bonfire
 * @author    Bonfire Dev Team
 * @copyright Copyright (c) 2011 - 2012, Bonfire Dev Team
 * @license   http://guides.cibonfire.com/license.html
 * @link      http://cibonfire.com
 * @since     Version 1.0
 * @filesource
 */

/**
 * Language Code Array
 *
 * Used by the language code helpers to map language codes to language names
 *
 * @package		Bonfire
 * @subpackage	Config
 * @category	Config
 * @author		San Diego State University
 */
$config['language_codes'] = array(
	'aa' => array('name' => 'afar',				'printable' => 'Afar'),
	'ab' => array('name' => 'abkhazian',		'printable' => 'Abkhazian'),
	'ae' => array('name' => 'avestan',			'printable' => 'Avestan'),
	'af' => array('name' => 'afrikaans',		'printable' => 'Afrikaans'),
	'ak' => array('name' => 'akan',				'printable' => 'Akan'),
	'am' => array('name' => 'amharic',			'printable' => 'Amharic'),
	'an' => array('name' => 'aragonese',		'printable' => 'Aragonese'),
	'ar' => array('name' => 'arabic',			'printable' => 'Arabic'),
	'as' => array('name' => 'assamese',			'printable' => 'Assamese'),
	'av' => array('name' => 'avaric',			'printable' => 'Avaric'),
	'ay' => array('name' => 'aymara',			'printable' => 'Aymara'),
	'az' => array('name' => 'azerbaijani',		'printable' => 'Azerbaijani'),
	'ba' => array('name' => 'bashkir',			'printable' => 'Bashkir'),
	'be' => array('name' => 'belarusian',		'printable' => 'Belarusian'),
	'bg' => array('name' => 'bulgarian',		'printable' => 'Bulgarian'),
	'bh' => array('name' => 'bihari',			'printable' => 'Bihari'),
	'bi' => array('name' => 'bislama',			'printable' => 'Bislama'),
	'bm' => array('name' => 'bambara',			'printable' => 'Bambara'),
	'bn' => array('name' => 'bengali',			'printable' => 'Bengali'),
	'bo' => array('name' => 'tibetan',			'printable' => 'Tibetan'),
	'br' => array('name' => 'breton',			'printable' => 'Breton'),
	'bs' => array('name' => 'bosnian',			'printable' => 'Bosnian'),
	'ca' => array('name' => 'catalan',			'printable' => 'Catalan'),
	'ce' => array('name' => 'chechen',			'printable' => 'Chechen'),
	'ch' => array('name' => 'chamorro',			'printable' => 'Charmorro'),
	'co' => array('name' => 'corsican',			'printable' => 'Corsican'),
	'cr' => array('name' => 'cree',				'printable' => 'Cree'),
	'cs' => array('name' => 'czech',			'printable' => 'Czech'),
	'cu' => array('name' => 'church_slavic',	'printable' => 'Church Slavic'),
	'cv' => array('name' => 'chuvash',			'printable' => 'Chuvash'),
	'cy' => array('name' => 'welsh',			'printable' => 'Welsh'),
	'da' => array('name' => 'danish',			'printable' => 'Danish'),
	'de' => array('name' => 'german',			'printable' => 'German'),
	'dv' => array('name' => 'divehi',			'printable' => 'Divehi'),
	'dz' => array('name' => 'dzongkha',			'printable' => 'Dzongkha'),
	'ee' => array('name' => 'ewe',				'printable' => 'Ewe'),
	'el' => array('name' => 'greek',			'printable' => 'Greek'),
	'en' => array('name' => 'english',			'printable' => 'English'),
	'eo' => array('name' => 'esperanto',		'printable' => 'Esperanto'),
	'es' => array('name' => 'spanish',			'printable' => 'Spanish'),
	'et' => array('name' => 'estonian',			'printable' => 'Estonian'),
	'eu' => array('name' => 'basque',			'printable' => 'Basque'),
	'fa' => array('name' => 'persian',			'printable' => 'Persian'),
	'ff' => array('name' => 'fulah',			'printable' => 'Fulah'),
	'fi' => array('name' => 'finnish',			'printable' => 'Finnish'),
	'fj' => array('name' => 'fijian',			'printable' => 'Fijian'),
	'fo' => array('name' => 'faroese',			'printable' => 'Faroese'),
	'fr' => array('name' => 'french',			'printable' => 'French'),
	'fy' => array('name' => 'western_frisian',	'printable' => 'Western Frisian'),
	'ga' => array('name' => 'irish',			'printable' => 'Irish'),
	'gd' => array('name' => 'gaelic',			'printable' => 'Gaelic'),
	'gl' => array('name' => 'galician',			'printable' => 'Galician'),
	'gn' => array('name' => 'guarani',			'printable' => 'Guarani'),
	'gu' => array('name' => 'gujarati',			'printable' => 'Gujarati'),
	'gv' => array('name' => 'manx',				'printable' => 'Manx'),
	'ha' => array('name' => 'hausa',			'printable' => 'Hausa'),
	'he' => array('name' => 'hebrew',			'printable' => 'Hebrew'),
	'hi' => array('name' => 'hindi',			'printable' => 'Hindi'),
	'ho' => array('name' => 'hiri_motu',		'printable' => 'Hiri Motu'),
	'hr' => array('name' => 'croatian',			'printable' => 'Croatian'),
	'ht' => array('name' => 'haitian',			'printable' => 'Haitian'),
	'hu' => array('name' => 'hungarian',		'printable' => 'Hungarian'),
	'hy' => array('name' => 'armenian',			'printable' => 'Armenian'),
	'hz' => array('name' => 'herero',			'printable' => 'Herero'),
	'ia' => array('name' => 'interlingua',		'printable' => 'Interlingua'),
	'id' => array('name' => 'indonesian',		'printable' => 'Indonesian'),
	'ie' => array('name' => 'interlingue',		'printable' => 'Interlingue (Occidental)'),
	'ig' => array('name' => 'igbo',				'printable' => 'Igbo'),
	'ii' => array('name' => 'sichuan_yi',		'printable' => 'Sichuan Yi'),
	'ik' => array('name' => 'inupiaq',			'printable' => 'Inupiaq'),
	'io' => array('name' => 'ido',				'printable' => 'Ido'),
	'is' => array('name' => 'icelandic',		'printable' => 'Icelandic'),
	'it' => array('name' => 'italian',			'printable' => 'Italian'),
	'iu' => array('name' => 'inuktitut',		'printable' => 'Inuktitut'),
	'ja' => array('name' => 'japanese',			'printable' => 'Japanese'),
	'jv' => array('name' => 'javanese',			'printable' => 'Javanese'),
	'ka' => array('name' => 'georgian',			'printable' => 'Georgian'),
	'kg' => array('name' => 'kongo',			'printable' => 'Kongo'),
	'ki' => array('name' => 'kikuyu',			'printable' => 'Kikuyu'),
	'kj' => array('name' => 'kuanyama',			'printable' => 'Kuanyama'),
	'kk' => array('name' => 'kazakh',			'printable' => 'Kazakh'),
	'kl' => array('name' => 'kalaallisut',		'printable' => 'Kalaallisut (Greenlandic)'),
	'km' => array('name' => 'central_khmer',	'printable' => 'Central Khmer'),
	'kn' => array('name' => 'kannada',			'printable' => 'Kannada'),
	'ko' => array('name' => 'korean',			'printable' => 'Korean'),
	'kr' => array('name' => 'kanuri',			'printable' => 'Kanuri'),
	'ks' => array('name' => 'kashmiri',			'printable' => 'Kashmiri'),
	'ku' => array('name' => 'kurdish',			'printable' => 'Kurdish'),
	'kv' => array('name' => 'komi',				'printable' => 'Komi'),
	'kw' => array('name' => 'cornish',			'printable' => 'Cornish'),
	'ky' => array('name' => 'kyrgyz',			'printable' => 'Kyrgyz'),
	'la' => array('name' => 'latin',			'printable' => 'Latin'),
	'lb' => array('name' => 'luxembourgish',	'printable' => 'Luxembourgish'),
	'lg' => array('name' => 'ganda',			'printable' => 'Ganda'),
	'li' => array('name' => 'limburgan',		'printable' => 'Limburgan'),
	'ln' => array('name' => 'lingala',			'printable' => 'Lingala'),
	'lo' => array('name' => 'lao',				'printable' => 'Lao'),
	'lt' => array('name' => 'lithuanian',		'printable' => 'Lithuanian'),
	'lu' => array('name' => 'luba_katanga',		'printable' => 'Luba-Katanga'),
	'lv' => array('name' => 'latvian',			'printable' => 'Latvian'),
	'mg' => array('name' => 'malagasy',			'printable' => 'Malagasy'),
	'mh' => array('name' => 'marshallese',		'printable' => 'Marshallese'),
	'mi' => array('name' => 'maori',			'printable' => 'Maori'),
	'mk' => array('name' => 'macedonian',		'printable' => 'Macedonian'),
	'ml' => array('name' => 'malayalam',		'printable' => 'Malayalam'),
	'mn' => array('name' => 'mongolian',		'printable' => 'Mongolian'),
	'mr' => array('name' => 'marathi',			'printable' => 'Marathi'),
	'ms' => array('name' => 'malay',			'printable' => 'Malay'),
	'mt' => array('name' => 'maltese',			'printable' => 'Maltese'),
	'my' => array('name' => 'burmese',			'printable' => 'Burmese'),
	'na' => array('name' => 'nauru',			'printable' => 'Nauru'),
	'nb' => array('name' => 'norwegian_bokmal',	'printable' => 'Norwegian BokmŒl'),
	'nd' => array('name' => 'north_ndebele',	'printable' => 'North Ndebele'),
	'ne' => array('name' => 'nepali',			'printable' => 'Nepali'),
	'ng' => array('name' => 'ndonga',			'printable' => 'Ndonga'),
	'nl' => array('name' => 'dutch',			'printable' => 'Dutch'),
	'nn' => array('name' => 'norwegian_nynorsk','printable' => 'Norwegian Nynorsk'),
	'no' => array('name' => 'norwegian',		'printable' => 'Norwegian'),
	'nr' => array('name' => 'south_ndebele',	'printable' => 'South Ndebele'),
	'nv' => array('name' => 'navajo',			'printable' => 'Navajo'),
	'ny' => array('name' => 'nyanja',			'printable' => 'Nyanja'),
	'oc' => array('name' => 'occitan',			'printable' => 'Occitan'),
	'oj' => array('name' => 'ojibwa',			'printable' => 'Ojibwa'),
	'om' => array('name' => 'oromo',			'printable' => 'Oromo'),
	'or' => array('name' => 'oriya',			'printable' => 'Oriya'),
	'os' => array('name' => 'ossetian',			'printable' => 'Ossetian'),
	'pa' => array('name' => 'panjabi',			'printable' => 'Panjabi'),
	'pi' => array('name' => 'pali',				'printable' => 'Pali'),
	'pl' => array('name' => 'polish',			'printable' => 'Polish'),
	'ps' => array('name' => 'pushto',			'printable' => 'Pushto'),
	'pt' => array('name' => 'portuguese',		'printable' => 'Portuguese'),
	'qu' => array('name' => 'quechua',			'printable' => 'Quechua'),
	'rm' => array('name' => 'romansh',			'printable' => 'Romansh'),
	'rn' => array('name' => 'rundi',			'printable' => 'Rundi'),
	'ro' => array('name' => 'romanian',			'printable' => 'Romanian'),
	'ru' => array('name' => 'russian',			'printable' => 'Russian'),
	'rw' => array('name' => 'kinyarwanda',		'printable' => 'Kinyarwanda'),
	'sa' => array('name' => 'sanskrit',			'printable' => 'Sanskrit'),
	'sc' => array('name' => 'sardinian',		'printable' => 'Sardinian'),
	'sd' => array('name' => 'sindhi',			'printable' => 'Sindhi'),
	'se' => array('name' => 'northern_sami',	'printable' => 'Northern Sami'),
	'sg' => array('name' => 'sango',			'printable' => 'Sango'),
	'si' => array('name' => 'sinhala',			'printable' => 'Sinhala'),
	'sk' => array('name' => 'slovak',			'printable' => 'Slovak'),
	'sl' => array('name' => 'slovenian',		'printable' => 'Slovenian'),
	'sm' => array('name' => 'samoan',			'printable' => 'Samoan'),
	'sn' => array('name' => 'shona',			'printable' => 'Shona'),
	'so' => array('name' => 'somali',			'printable' => 'Somali'),
	'sq' => array('name' => 'albanian',			'printable' => 'Albanian'),
	'sr' => array('name' => 'serbian',			'printable' => 'Serbian'),
	'ss' => array('name' => 'swati',			'printable' => 'Swati'),
	'st' => array('name' => 'southern_sotho',	'printable' => 'Southern Soho'),
	'su' => array('name' => 'sundanese',		'printable' => 'Sundanese'),
	'sv' => array('name' => 'swedish',			'printable' => 'Swedish'),
	'sw' => array('name' => 'swahili',			'printable' => 'Swahili'),
	'ta' => array('name' => 'tamil',			'printable' => 'Tamil'),
	'te' => array('name' => 'telugu',			'printable' => 'Telugu'),
	'tg' => array('name' => 'tajik',			'printable' => 'Tajik'),
	'th' => array('name' => 'thai',				'printable' => 'Thai'),
	'ti' => array('name' => 'tigrinya',			'printable' => 'Tigrinya'),
	'tk' => array('name' => 'turkmen',			'printable' => 'Turkmen'),
	'tl' => array('name' => 'tagalog',			'printable' => 'Tagalog'),
	'tn' => array('name' => 'tswana',			'printable' => 'Tswana'),
	'to' => array('name' => 'tonga',			'printable' => 'Tonga (Tonga Islands)'),
	'tr' => array('name' => 'turkish',			'printable' => 'Turkish'),
	'ts' => array('name' => 'tsonga',			'printable' => 'Tsonga'),
	'tt' => array('name' => 'tatar',			'printable' => 'Tatar'),
	'tw' => array('name' => 'twi',				'printable' => 'Twi'),
	'ty' => array('name' => 'tahitian',			'printable' => 'Tahitian'),
	'ug' => array('name' => 'uighur',			'printable' => 'Uighur'),
	'uk' => array('name' => 'ukrainian',		'printable' => 'Ukrainian'),
	'ur' => array('name' => 'urdu',				'printable' => 'Urdu'),
	'uz' => array('name' => 'uzbek',			'printable' => 'Uzbek'),
	've' => array('name' => 'venda',			'printable' => 'Venda'),
	'vi' => array('name' => 'vietnamese',		'printable' => 'Vietnamese'),
	'vo' => array('name' => 'volapuk',			'printable' => 'VolapŸk'),
	'wa' => array('name' => 'walloon',			'printable' => 'Walloon'),
	'wo' => array('name' => 'wolof',			'printable' => 'Wolof'),
	'xh' => array('name' => 'xhosa',			'printable' => 'Xhosa'),
	'yi' => array('name' => 'yiddish',			'printable' => 'Yiddish'),
	'yo' => array('name' => 'yoruba',			'printable' => 'Yoruba'),
	'za' => array('name' => 'zhuang',			'printable' => 'Zhuang'),
	'zh' => array('name' => 'chinese',			'printable' => 'Chinese'),
	'zu' => array('name' => 'zulu',				'printable' => 'Zulu'),
);
